// This file was autogenerated by /Users/ygwang/src/closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../ppzsite/poems_html5_app/js/poems.js', ['poems'], ['poems.Viewport'], false);
goog.addDependency('../../../ppzsite/poems_html5_app/js/viewport.js', ['poems.Viewport'], ['goog.dom', 'goog.events', 'goog.events.EventType', 'goog.style'], false);
