// This file was autogenerated by /Users/ygwang/src/closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../ppzsite/poems_html5_app/js/poems.js', ['poems'], [], false);
