baseURL: "https://ygwang.info/"
theme: "hugo-PaperMod"
defaultContentLanguage: "zh"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

pagination:
  pagerSize: 10

minify:
  disableXML: true
  minifyOutput: true

languages:
  zh:
    languageCode: "zh-CN"
    languageDirection: "ltr"
    languageName: "Simplified Chinese"
    title: "半轻人小站：王咏刚的诗文、小说、笔记、创意"
    weight: 1

params:
  env: production
  defaultTheme: auto # dark, light
  disableThemeToggle: false
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowPageNums: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false
  DateFormat: "2006年1月2日"

  profileMode:
    enabled: true
    title: "种竹可侔千户<br>拥书不假百城"
    subtitle: "王咏刚，笔名“半轻人”。有诗百余首。有文章、小说、杂书若干。发布或开源过几个有趣的小工具。技术宅，逻辑控。用emacs写小说，用平水韵下酒。"
    imageUrl: "images/seal_slogan.svg"
    imageTitle: "拥书百城"
    imageWidth: 160
    imageHeight: 160
    buttons:
      - name: 诗歌
        url: "/poems"
      - name: 小说
        url: "/fictions"
      - name: 笔记杂谈
        url: "/notes"

  label:
    text: "半轻人小站"
    icon: "images/seal_me_xie.svg"
    iconHeight: 32

  assets:
    favicon: "images/seal_me_xie.svg"

  socialIcons:
    - name: "GitHub"
      url: "https://github.com/wixette/"
    - name: "linkedIn"
      url: "https://www.linkedin.com/in/wixette/"
    - name: "X"
      url: "https://x.com/wixette"
    - name: "zhihu"
      url: "https://www.zhihu.com/people/ygwang"
    - name: "instagram"
      url: "https://www.instagram.com/wixette"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

menu:
  main:
    - identifier: poems
      name: 诗歌
      url: /poems/
      weight: 10
    - identifier: fictions
      name: 小说
      url: /fictions/
      weight: 20
    - identifier: notes
      name: 笔记杂谈
      url: /notes/
      weight: 30

  # Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true

markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai
  goldmark:
    extensions:
      cjk:
      eastAsianLineBreaks: true
      eastAsianLineBreaksStyle: simple
      enable: true
      escapedSpace: false
    renderer:
      unsafe: true

