baseURL = 'https://ygwang.info/'
title = '咏刚的诗'
theme = 'PaperMod'
defaultContentLanguage = "zh-cn"

[languages]
  [languages.zh-cn]
    languageCode = 'zh-CN'
    languageDirection = 'ltr'
    languageName = 'Simplified Chinese'
    weight = 1

[params]
  DateFormat = '2006年1月2日'
